name: Greeting variable

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      SupabaseUrl: ${{ vars.VITE_SUPABASE_URL }}
      SupabaseUrlSecret: ${{ vars.VITE_SUPABASE_URL }}
    steps:
      - name: "Say Hello Variable"
        run: echo "Greeting $SupabaseUrlSecret $SupabaseUrl"
