name: Greeting variable

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Github: ${{ secrets.GITHUB_TOKEN }}
      SupabaseUrl: ${{ secrets.VITE_SUPABASE_URL }}
    steps:
      - name: "Say Hello Variable"
        run: echo "Greeting $Github $SupabaseUrl"
