name: Simple Vars and Secrets

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Echo vars and secrets
        env:
          MY_VAR: ${{ vars.MY_VAR }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "VAR = $MY_VAR"
          echo "SECRET = $MY_SECRET"
